# Generated by Django 2.1.5 on 2019-02-11 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('summary_text', models.TextField(max_length=100, verbose_name='本文')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.Book', verbose_name='書籍')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='執筆者')),
            ],
            options={
                'db_table': 'summary',
            },
        ),
    ]
